### ISSUE TITLE
Saving signature without giving signature

### ISSUE THREAD

**Issue by avulavenkateswar** [keirbowden/sigcapapp#19]
Hi Team,

We are able to save the signature record, without giving signature. Please fix this issue ASAP.

Regards,
Venkat

**Comment by keirbowden** [comment]
I suspect this is something that has been introduced by the Summer 19 release of Salesforce, as this definitely wasn't possible in Spring. 

Signature capture is a free component that I maintain in my spare time, so I can't give you an ETA for a fix, but I will update this issue when it is done.

**Comment by avulavenkateswar** [comment]
Hi,

Thank you for quick response. It will be great if you fix it quickly. We are getting complaints from Business regularly.

Regards,
Venkat

**Comment by keirbowden** [comment]
This is now fixed, plus another bug that meant if you started a signature and then cleared the canvas you could save the empty image. Upgrade via the app exchange listing at : https://appexchange.salesforce.com/appxListingDetail?listingId=a0N30000000q5XOEAY
