### ISSUE TITLE
Signature box not editable on mobile device. 

### ISSUE THREAD

**Issue by sajal-sethi** [keirbowden/sigcapapp#2]
Unable to sign on salesforce1 using iPhone or iPad. The signature box appears read-only. 
On clicking 'Save', an empty image gets created and attached against the record.
Works fine on laptop though.

**Comment by keirbowden** [comment]
Is the locker service enabled on the org where you are seeing this? (Go to Setup -> Critical Updates and see if Lightning LockerService Security is enabled). At the moment the locker service doesn't surface touch events and therefore breaks the component. You can see more at the [Stack Exchange](http://salesforce.stackexchange.com/questions/129113/lockerservice-touch-events-and-coordinates/129168#129168) post.

**Comment by sajal-sethi** [comment]
The update 'Enable Lightning LockerService Security for Communities' is showing as 'Not Activated'.
Could there be any other factor ?

**Comment by keirbowden** [comment]
The locker service for communities is a different feature activation to the locker service - I am talking about the update named 'Enable Lightning LockerService Security' - if that is activated then you won't be able to create a signature as it blocks the touch events from reaching my component.

**Comment by keirbowden** [comment]
Closing as no response for nearly two years.
