### ISSUE TITLE
Signature does not save as a related file.

### ISSUE THREAD

**Issue by uniquelycloud** [keirbowden/sigcapapp#28]
Hello I have tried in both the desktop version of Salesforce and the Salesforce app.
I sign and save. 
But when I go back to the record, the signature isn't any where to be found.

I have looked in notes and attachments and files but it is not saved there nor to the component itself.

**Comment by keirbowden** [comment]
Hello.

That's odd. I'd expect to see an error surfaced if the save failed.  I assume you've refreshed the page, as the files or attachments related lists don't get auto updated.

A few questions :

Which browser/device is this happening on?
Is this a new install or has it just started happening to an existing component?
Which version of the package do you have installed?
Have you configured the component to save files or attachments?
If you open the developer console and go through the save process, do you see any exceptions in the debug log?

In the debug log you should be able to see the DML statement for the insertion, something like `09:38:04:882 DML_BEGIN [157]|Op:Insert|Type:ContentDocumentLink|Rows:1` for Files or `09:32:20:822 DML_BEGIN [83]|Op:Insert|Type:Attachment|Rows:1` for Attachments. Does either of those appear?

Cheers

--

Keir

Please note BrightSIGN is a free component that I maintain outside of working hours, so there will be delays in responses.

**Comment by uniquelycloud** [comment]
Hi

iPhone 12 Max Pro Salesforce App.
Google Chrome latest browser version.

Brand new install Monday 21 Feb.
Version 3.5

I have review your guide and cannot locate any instruction on configuring the component to save the signature? https://appexchange.salesforce.com/partners/servlet/servlet.FileDownload?file=00P4V00000rHnK5UAK#:~:text=BrightSIGN%20is%20a%20Lightning%20Component,image%20against%20a%20Salesforce%20record. 

there are no errors in the debug log

**Comment by keirbowden** [comment]
Hello again,

Thanks for the answers. Page 4 of the guide details how to configure the component to save attachments or files, via the `saveAttachment` property - if you haven't changed it, the default will be attachments.

Did you see the DML statement in the debug log? If there are no errors then I'd expect to see a line similar to 

`09:32:20:822 DML_BEGIN [83]|Op:Insert|Type:Attachment|Rows:1`

Attachments are deprecated in Lightning Experience (per : https://help.salesforce.com/s/articleView?id=000314087&type=1) so it might be worth setting the `saveAttachment` property to `false` to see if you have better luck with Files.

Cheers

**Comment by uniquelycloud** [comment]
Sorry I am not a developer?

This is way over my head.

**Comment by keirbowden** [comment]
Hello again,

You don't need to be a developer to switch over to Files. If you are using Lightning App Builder, when you click on the BrightSIGN component you'll see the attributes for configuration on the right hand side. Uncheck the box for Save Attachments and the next image will be saved as a File.

**Comment by uniquelycloud** [comment]
Hello,
I have applied this change and it's still not appearing in files. 

The component is placed in the Task Page Layout.  The related record is the Account.
I would expect to see the signature saved in the files on the Account then.

**Comment by uniquelycloud** [comment]
Ok I have it now appearing on Tasks not Accounts... thanks!
