### ISSUE TITLE
Fire event when signature captured

### ISSUE THREAD

**Issue by keirbowden** [keirbowden/sigcapapp#3]
Include record id and maybe timestamp.

**Comment by camisotro** [comment]
Any updates on this? Would be great for an upcoming project but we need to be able to receive some sort of event to handle once it's captured.

**Comment by keirbowden** [comment]
I'm afraid not. I probably won't be adding any more enhancements until 2018.

**Comment by camisotro** [comment]
Thanks for the update. If we can't come up with a workaround, I guess we'll have to roll something from scratch then.

**Comment by keirbowden** [comment]
A BGSIGCAP:SignatureCapturedEvt event is now fired when a signature is successfully captured. It includes a recordId attribute that contains the id of the record the signature was captured against (i.e. the record that owns the signature file).

V1.30 on the app exchange has this functionality, and there is an example of handing the event in the repo.
