### ISSUE TITLE
Flow Component “No id parameter provided in URL”

### ISSUE THREAD

**Issue by TlewisGP** [keirbowden/sigcapapp#34]
I have a screen flow that creates a record, then a "get records" element for the record id. This is followed by another screen element using the signature component, with the record id from the previous "get records" element. I have tried a couple of variations of this set up and in all cases I get “No id parameter provided in URL”. 
If I run the flow debug by entering an existing record id, it works perfectly. 
The issue seems to arise when it is creating the record new. 

^I hope that all made sense. Any guidance/troubleshooting ideas on this is greatly appreciated! 
![image](https://user-images.githubusercontent.com/117190227/199296725-870e31bf-3e31-4c36-8b0c-5d9e3f68c5bc.png)
![image](https://user-images.githubusercontent.com/117190227/199297216-ea21035d-ca4d-4b1b-b0a4-ae87a75a7934.png)

**Comment by keirbowden** [comment]
Hi Taylor,

The error message (which isn't fantastic by the way, so I'm going to improve that) is shown when the component's `recordId` attribute (which maps to the `Record Id` design attribute in the screenshot) is null. This suggests that `{!NewRRSARecordID.id}` is evaluating to null. 

Is NewRRSARecordID a record variable? The name suggests that it's already an ID. 

To debug, I would put a simple output screen in the flow that prints the value of `{!NewRRSARecordID.id}` before the signature capture element - that way BrightSIGN is out of the equation.

Give that a shot and let me know how you get on.

**Comment by TlewisGP** [comment]
Hi! I am so sorry I realized I never gave you the update! I did get it working but ran into another issue. You already have the other issue logged as a future enhancement! This can be closed :)
