### ISSUE TITLE
Error in Apex trying to use the BrightSIGN in User Object.

### ISSUE THREAD

**Issue by michaelsimini-ciandt** [keirbowden/sigcapapp#35]
Im getting this apex error:

`This page has an error. You might just need to refresh it. Error in $A.getCallback() [self.toggleClass is not a function] Callback failed: apex://BGSIGCAP.SignatureCaptureController/ACTION$SaveSignatureFile Failing descriptor: {markup://BGSIGCAP:SignatureCapture}`

Im using the exacly version of the component: 
https://github.com/keirbowden/sigcapapp/tree/master/src/aura/SigCapFlowWithFinish
inside a FLOW.

Parameters Im using:

API Name
ICA_Sign

*Canvas Height
250px
*Canvas Width
100%

Capture Button Label
Capture Signature

Clear Button Label
Clear

Complete Message
Here is the captured signature

Enter Message
Sign here please

File Name
My Digital Signature.png

Record Id
{!$User.Id}

Save Attachment
{!$GlobalConstant.False}

Save Button Label
Save

Skip to capture?
{!$GlobalConstant.True}

Start Message
Click the 'Capture Signature' button to begin

**Comment by michaelsimini-ciandt** [comment]
the image file its being created inside the files section on the User record, even with the error presented on the flow.

![image](https://github.com/keirbowden/sigcapapp/assets/90412686/9c5bac9b-ae98-4503-95d7-65c83625a140)

**Comment by michaelsimini-ciandt** [comment]
but the error blocks the event ``SignatureCapturedEvt`` , avoiding the expected behaviour for the [SigCapFlowWithFinish](https://github.com/keirbowden/sigcapapp/tree/master/src/aura/SigCapFlowWithFinish), and showing an infinity loop loader png

**Comment by keirbowden** [comment]
Hello - this is something that broke after a Salesforce release and was fixed in version 3.6, released at the end of May. Can you update to the latest version via the app exchange and see if you are still encountering a problem.

**Comment by michaelsimini-ciandt** [comment]
thanks! it worked after the update!
