### ISSUE TITLE
Button Text not configurable

### ISSUE THREAD

**Issue by perryhoekstra** [keirbowden/sigcapapp#6]
The buttons such as Save Signature, Save and Clear are not configurable (similar to the messages) which means you cannot assign Custom Labels (multi-lingual translation).

**Comment by keirbowden** [comment]
These are configurable in the current version from the app exchange - if you are using the lightning app builder to add it you'll see the design attributes. If via code, the attributes are 'saveButtonLabel' and 'clearButtonLabel'. 

The example action : https://github.com/keirbowden/sigcapapp/blob/master/src/aura/SigCapAction/SigCapAction.cmp defines custom text for these if you need to see an example.
