### ISSUE TITLE
Salesforce Professional Edition

### ISSUE THREAD

**Issue by SFWannabe** [keirbowden/sigcapapp#8]
HI great project... forgive my ignorance and lack of  understanding, but whats stopping this running in SF Pro Edition?

I can go through all the setup to get the app installed, says installed.

Then when i set up the quick action, i get this error:

No CONTROLLER named js://BGSIGCAP.SignatureCapture found

I have lightning running, also salesforce1 on win mobile...

**Comment by keirbowden** [comment]
While we don't officially support professional edition, I've tested in professional edition trial org and it's working for me. It sounds like your org might have apex disabled, which sometimes happen if Salesforce do a bespoke deal for your company.

**Comment by SFWannabe** [comment]
yes thanks, I managed to figure it out. needed to enable My Domain and register a Domain - thanks, great app. J
